//DBL Structure
const a1= [
    {id:"a1_01",
    subcategory:"DBL Author"},
    {id:"a1_02",
    subcategory:"DBL Last Update"},
    {id:"a1_03",
    subcategory:"Bulding ID - national cadaster"},
    {id:"a1_04",
    subcategory:"Building ID - Inspire"},
    {id:"a1_05",
    subcategory:"Building ID-energy suppliers"},
    {id:"a1_06",
    subcategory:"Property ID (legal/fiscal registration)"},
    {id:"a1_07",
    subcategory:"Ownership type"},
    {id:"a1_08",
    subcategory:"Building category"},
    {id:"a1_09",
    subcategory:"Building ID-energy suppliers"},
    {id:"a1_10",
    subcategory:"Building user information"},
    {id:"a1_11",
    subcategory:"Year of construction"},
    {id:"a1_12",
    subcategory:"Year of renovation"},
    {id:"a1_13",
    subcategory:"Address"},
    {id:"a1_13",
    subcategory:"Climate data (Zone)"},
    {id:"a1_13",
    subcategory:"Address"},
    {id:"a1_13",
    subcategory:"Address"},
    {id:"a1_13",
    subcategory:"Address"},

    ]
export const a2=[
    {id:"a2_02",
    subCategory:"Facades",
    subcategoryIndicators:[
        {id:"a2_02_00",subcatIndicatorName:"Facade Element",units:""},
        {id:"a2_02_01",subcatIndicatorName:"Facade Covering",units:""},
        {id:"a2_02_02",subcatIndicatorName:"Facade Main Structure",units:""},
        {id:"a2_02_03",subcatIndicatorName:"Facade Surface Area", units:"m2"},
        {id:"a2_02_04",subcatIndicatorName:"Facade U value", units:"W/m2*K"},
        {id:"a2_02_05",subcatIndicatorName:"Facade Insulation (Y/N)",units:""},
        {id:"a2_02_06",subcatIndicatorName:"Facade Thickness of insulation", units:"mm"},
        {id:"a2_02_07",subcatIndicatorName:"Facade Insulation Type",units:""},
        {id:"a2_02_08",subcatIndicatorName:"Facade Insulation Thermal Conductivity",units:"W/m*K"},
        {id:"a2_02_09",subcatIndicatorName:"Facade Layer Material 1",units:""},
        {id:"a2_02_10",subcatIndicatorName:"Facade Layer Thermal Conductivity 1"},
        {id:"a2_02_11",subcatIndicatorName:"Facade Layer Thickness 1"},
    ]},
    {id:"a2_02",
    subCategory:"Windows",
    subcategoryIndicators:[
        {id:"a2_03_00",subcatIndicatorName:"Window Element",units:""},
        {id:"a2_03_01",subcatIndicatorName:"Window Frame Material",units:""},
        {id:"a2_03_02",subcatIndicatorName:"Window Glass Composition",units:""},
        {id:"a2_03_03",subcatIndicatorName:"Window Surface Area", units:"m2"},
        {id:"a2_03_04",subcatIndicatorName:"Window Frame Factor", units:"%"},
        {id:"a2_03_05",subcatIndicatorName:"Window U-Value Frame",units:"W/m2*K"},
        {id:"a2_03_06",subcatIndicatorName:"Window U-Value Glazing", units:"W/m2*K"},
        {id:"a2_03_07",subcatIndicatorName:"Window g-Value Glazing",units:""},
        {id:"a2_03_08",subcatIndicatorName:"Window Glazed facade",units:"%"},
        {id:"a2_03_09",subcatIndicatorName:"Window Orientation",units:""},
        {id:"a2_03_10",subcatIndicatorName:"Window Protection Elements/ Sheltered Sides",units:""},
        {id:"a2_03_11",subcatIndicatorName:"Window Shutters and Solar Protection",units:""},
    ]},
    {id:"a2_02",
    subCategory:"Floors",
    subcategoryIndicators:[
        {id:"a2_04_00",subcatIndicatorName:"Floor Element",units:""},
        {id:"a2_04_01",subcatIndicatorName:"Nº Heated Floors",units:""},
        {id:"a2_04_02",subcatIndicatorName:"Floor Surface Area",units:"m2"},
        {id:"a2_04_03",subcatIndicatorName:"Floor U-Value",units:"W/m2*K"},
        {id:"a2_04_04",subcatIndicatorName:"Floor Structure Slab",units:""},
        {id:"a2_04_05",subcatIndicatorName:"Floor Insulation (Y/N)",units:""},
        {id:"a2_04_06",subcatIndicatorName:"Floor Insulation Thickness",units:""},
        {id:"a2_04_07",subcatIndicatorName:"Floor Insulation Type",units:""},
        {id:"a2_04_08",subcatIndicatorName:"Floor Insulation Thermal Conductivity",units:""},
        {id:"a2_04_09",subcatIndicatorName:"Floor Layer Material 1",units:""},
        {id:"a2_04_10",subcatIndicatorName:"Floor Layer Thermal Conductivity 1",units:""},
        {id:"a2_04_11",subcatIndicatorName:"Floor Layer Thickness 1",units:""},
    ]},
    {id:"a2_03",
    subCategory:"Roofs",
    subcategoryIndicators:[
        {id:"a2_05_00",subcatIndicatorName:"Roof Element",units:""},
        {id:"a2_05_01",subcatIndicatorName:"Roof Surface Area",units:"m2"},
        {id:"a2_05_02",subcatIndicatorName:"Roof U-Value",units:"W/m2*K"},
        {id:"a2_05_03",subcatIndicatorName:"Roof Main Structure",units:""},
        {id:"a2_05_04",subcatIndicatorName:"Roof Insulation (Y/N)",units:""},
        {id:"a2_05_05",subcatIndicatorName:"Roof Insulation Thickness",units:""},
        {id:"a2_05_06",subcatIndicatorName:"Roof Insulation Type",units:""},
        {id:"a2_05_07",subcatIndicatorName:"Roof Insulation Thermal Conductivity",units:""},
        {id:"a2_05_08",subcatIndicatorName:"Roof Layer Material 1",units:""},
        {id:"a2_05_09",subcatIndicatorName:"Roof Layer Thermal Conductivity 1",units:""},
        {id:"a2_05_10",subcatIndicatorName:"Roof Layer Thickness 1",units:""},
    ]},
    {id:"a2_04",
    subCategory:"Material Inventory",
    subcategoryIndicators:[
        {id:"a2_06_00",subcatIndicatorName:"Roof Element",units:""},
        {id:"a2_06_01",subcatIndicatorName:"Roof Surface Area",units:"m2"},
        {id:"a2_06_02",subcatIndicatorName:"Roof U-Value",units:"W/m2*K"},
        {id:"a2_06_03",subcatIndicatorName:"Roof Main Structure",units:""},
        {id:"a2_06_04",subcatIndicatorName:"Roof Insulation (Y/N)",units:""},
        {id:"a2_06_05",subcatIndicatorName:"Roof Insulation Thickness",units:""},
        {id:"a2_06_06",subcatIndicatorName:"Roof Insulation Type",units:""},
        {id:"a2_06_07",subcatIndicatorName:"Roof Insulation Thermal Conductivity",units:""},
        {id:"a2_06_08",subcatIndicatorName:"Roof Layer Material 1",units:""},
        {id:"a2_06_09",subcatIndicatorName:"Roof Layer Thermal Conductivity 1",units:""},
        {id:"a2_06_10",subcatIndicatorName:"Roof Layer Thickness 1",units:""},
    ]},
    {id:"a2_05",
    subCategory:"Material Inventory",
    subcategoryIndicators:[
        {id:"a2_06_00",subcatIndicatorName:"Roof Element",units:""},
        {id:"a2_06_01",subcatIndicatorName:"Roof Surface Area",units:"m2"},
        {id:"a2_06_02",subcatIndicatorName:"Roof U-Value",units:"W/m2*K"},
        {id:"a2_06_03",subcatIndicatorName:"Roof Main Structure",units:""},
        {id:"a2_06_04",subcatIndicatorName:"Roof Insulation (Y/N)",units:""},
        {id:"a2_06_05",subcatIndicatorName:"Roof Insulation Thickness",units:""},
        {id:"a2_06_06",subcatIndicatorName:"Roof Insulation Type",units:""},
        {id:"a2_06_07",subcatIndicatorName:"Roof Insulation Thermal Conductivity",units:""},
        {id:"a2_06_08",subcatIndicatorName:"Roof Layer Material 1",units:""},
        {id:"a2_06_09",subcatIndicatorName:"Roof Layer Thermal Conductivity 1",units:""},
        {id:"a2_06_10",subcatIndicatorName:"Roof Layer Thickness 1",units:""},
    ]},
];
export const a3=[
    {id:"a3_02",
    subCategory:"Heating System",
    subcategoryIndicators:[
        {id:"a3_02_00",subcatIndicatorName:"Heating System Element",units:""},
        {id:"a3_02_01",subcatIndicatorName:"Type of heating System",units:""},
        {id:"a3_02_02",subcatIndicatorName:"Number of units installed",units:""},
        {id:"a3_02_03",subcatIndicatorName:"Generator x", units:""},
        {id:"a3_02_04",subcatIndicatorName:"Average efficiency rate of generation at X", units:"W/m2*K"},
        {id:"a3_02_05",subcatIndicatorName:"Brand Name",units:""},
        {id:"a3_02_06",subcatIndicatorName:"Energy label", units:"mm"},
        {id:"a3_02_07",subcatIndicatorName:"Age",units:""},
        {id:"a3_02_08",subcatIndicatorName:"Last inspection",units:"W/m*K"},
        {id:"a3_02_09",subcatIndicatorName:"Nominal electrical power",units:""},
        {id:"a3_02_10",subcatIndicatorName:"Energy source"},
        {id:"a3_02_11",subcatIndicatorName:"Heat generation"},
        {id:"a3_02_12",subcatIndicatorName:"Net energy for space heating"},
        {id:"a3_02_13",subcatIndicatorName:"Certificate warrantyn"},
        {id:"a3_02_14",subcatIndicatorName:"Manual"},
    ]},
    {id:"a3_03",
    subCategory:"Cooling System",
    subcategoryIndicators:[
        {id:"a3_03_00",subcatIndicatorName:"Cooling System Element",units:""},
        {id:"a3_03_01",subcatIndicatorName:"Type of cooling system",units:""},
        {id:"a3_03_02",subcatIndicatorName:"Number of units installed",units:""},
        {id:"a3_03_03",subcatIndicatorName:"Generator x", units:""},
        {id:"a3_03_04",subcatIndicatorName:"Average efficiency rate of generation at X", units:"W/m2*K"},
        {id:"a3_03_05",subcatIndicatorName:"Brand Name",units:""},
        {id:"a3_03_06",subcatIndicatorName:"Energy label", units:"mm"},
        {id:"a3_03_07",subcatIndicatorName:"Age",units:""},
        {id:"a3_03_08",subcatIndicatorName:"Last inspection",units:"W/m*K"},
        {id:"a3_03_09",subcatIndicatorName:"Nominal electrical power",units:""},
        {id:"a3_03_10",subcatIndicatorName:"Nominal thermal power"},
        {id:"a3_03_11",subcatIndicatorName:"Fuel type"},
        {id:"a3_03_12",subcatIndicatorName:"Storage"},
        {id:"a3_03_13",subcatIndicatorName:"Certificate/Warranty"},
        {id:"a3_03_14",subcatIndicatorName:"Manual"},
    ]},
    {id:"a3_04",
    subCategory:"Domestic Hot Water",
    subcategoryIndicators:[
        {id:"a3_04_00",subcatIndicatorName:"DHW System Element",units:""},
        {id:"a3_04_01",subcatIndicatorName:"Boiler Type",units:""},
        {id:"a3_04_02",subcatIndicatorName:"Tank Size",units:""},
        {id:"a3_04_03",subcatIndicatorName:"Tank Age", units:""},
        {id:"a3_04_04",subcatIndicatorName:"Fuel Type", units:"W/m2*K"},
        {id:"a3_04_05",subcatIndicatorName:"System Efficiency",units:""},
        {id:"a3_04_06",subcatIndicatorName:"Service Present", units:"mm"},
        {id:"a3_04_07",subcatIndicatorName:"Manual",units:""},
        {id:"a3_04_08",subcatIndicatorName:"Certificate warranty",units:"W/m*K"},
        {id:"a3_04_09",subcatIndicatorName:"Primary pipework insulation present",units:""},
    ]},
    {id:"a3_05",
    subCategory:"Ventilation System",
    subcategoryIndicators:[
        {id:"a3_05_00",subcatIndicatorName:"Ventilation System Elements",units:""},
        {id:"a3_05_01",subcatIndicatorName:"Typology of ventilation System",units:""},
        {id:"a3_05_02",subcatIndicatorName:"Filter type/class",units:""},
        {id:"a3_05_03",subcatIndicatorName:"Airflow control ar room level (Y/N)", units:""},
        {id:"a3_05_04",subcatIndicatorName:"Heat recovery (Y/N)", units:"W/m2*K"},
        {id:"a3_05_05",subcatIndicatorName:"Heat recovery efficiency",units:""},
        {id:"a3_05_06",subcatIndicatorName:"Heat recovery-Operational thermal efficienccy ", units:"mm"},
        {id:"a3_05_07",subcatIndicatorName:"Temperature of ventilation return air",units:""},
        {id:"a3_05_08",subcatIndicatorName:"Temperature of ventilation supply air",units:"W/m*K"},
        {id:"a3_05_09",subcatIndicatorName:"Ventilation airflow rate",units:""},
        {id:"a3_05_10",subcatIndicatorName:"Nominal thermal power"},
        {id:"a3_05_11",subcatIndicatorName:"Fuel type"},
        {id:"a3_05_12",subcatIndicatorName:"Storage"},
        {id:"a3_05_13",subcatIndicatorName:"Certificate/Warranty"},
        {id:"a3_05_14",subcatIndicatorName:"Manual"},
    ]},
]